### ISSUE TITLE
You have spectacularly avoided answering "How can it be free?"

### ISSUE THREAD

**Issue by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [ihucos/counter.dev#114]
My local politicians would like your number.

**Comment by ihucos** [comment]
Funny. But I prefer dry and technical. Let's try to find an inclusive and somewhat professional tone.

So we are talking about this section in the README: https://github.com/ihucos/counter.dev#how-can-it-be-free
In my perspective I list there concrete technical design decision that leads to very low operational costs. Some I see as quite radical as for example using redis as the primary database.

Here is the CPU usage of the VPS for the last 30 days. It is a "Nanode 1 GB"

![screenie](https://user-images.githubusercontent.com/2066372/225489536-35c8e9bc-62ae-457c-89ff-5dc904ab4a78.jpg)

So we have a CPU peaking out at 24% on a 5$ VPS (See pricing here: https://www.linode.com/pricing/)
In case you are interested the server is currently using 218.6 megabyte of memory. The hard drive space is at 6.1 Gigabyte of meagre 24 Gigabyte.

To say some numbers on the usage side: There are some hundreds of active users and some millions of unique tracked pageviews in the last 30 days.


To be fair the domain is a bit more expensive and I am also paying for a VPS snapshot service. These are the costs. Of course there is the time I put in, if you put a value at that we get a different order of magnitude. So is it free? Well, I guess no, there are resources involved in serving you. Is it working already since over two years? Yes. Will it continue to work for many years to come? I guarantee it.

I hope that was concrete enough. I honestly am super happy about every single donation for the project.

Cheers.

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
> [...] Let's try to find an inclusive and somewhat professional tone.
> 
Sorry I'm off the clock when I github...

> So we are talking about this section in the README: https://github.com/ihucos/counter.dev#how-can-it-be-free In my perspective I list there concrete technical design decision that leads to very low operational costs. Some I see as quite radical as for example using redis as the primary database.
>
> [...]
> I hope that was concrete enough. I honestly am super happy about every single donation for the project.
> 
> Cheers.

Yes, that info, which is both dry and technical, makes a lot of sense. Compared to 'it's a small app, don't worry about it' (paraphrasing).  I think would be a value add to that section.

**Comment by ihucos** [comment]
>  I think would be a value add to that section.

Ahh you mean to put the information about the real world resource usage and service usage in the README? Yeah, that would actually make sense.

**Comment by ihucos** [comment]
I updated the README. Thanks for the issue.
