### ISSUE TITLE
counter.dev is down! Domain expired, need to renew. 

### ISSUE THREAD

**Issue by saif71** [ihucos/counter.dev#124]
As the title suggests. Need to renew the domain name.
![image](https://github.com/ihucos/counter.dev/assets/6561498/91b6b2ce-8161-4130-92c4-8069bdf0923e)

Who.is: https://who.is/whois/counter.dev

**Comment by DanHakimi** [comment]
[DNS Migration is in progress!](https://twitter.com/DevCounter/status/1709212441328951694)

**Comment by ihucos** [comment]
That is embarrassing but exactly what is happening.

I even made it worse by thinking "OK, there is already down time, let me migrate to another registrar and see that everything works there". As I learned this takes time. I tried to renew my domain with my old registrar but it says its not possible because I am in the process of migrating. I could request with my new registrars to cancel the migration but imagine this would makes matters only worse.

Obviously not a good situation I brought the service into.  I am happy about input what to do. I believe at this point the best option is to wait.

**Comment by ihucos** [comment]
The new registrar - Namecheap - seems to be very responsive. The old one - Gandi - not at all.
Maybe I wait until the afternoon (Now is morning for me). If my old registrar - Gandi - is not able to approve the transfer in order to make it faster I will consider trying my luck cancelling.

Apologies for two grave mistakes that lead to this situations. Letting the domain expire and then trying to transfer an expired domain. If you have any questions, concerns or things to say I am here for it.

**Comment by ihucos** [comment]
Current status. Gandi was able to unblock me via Twitter: https://twitter.com/DevCounter/status/1709499729191616648

With a little luck it could start working in one hourish.

**Comment by saif71** [comment]
@ihucos I'm 100% with you. You don't need to apologies as this is pretty common in tech world. I mean multi-billion-dollar companies sometime have unplanned downtime. (Hello Amazon, Netflix, Cloudflare)

Cheers!

**Comment by ihucos** [comment]
Thanks @saif71

**Comment by ihucos** [comment]
Current status: Domain transfer complete, waiting for things to propagate.

**Comment by ihucos** [comment]
Now this time with my primary email address that I regularly check and auto renewal enabled :relieved:

**Comment by saif71** [comment]
Thanks for your hard work! Really appreciate it.
